In [26]:
"""preprocessing activities includes in sklearn preprocessing"""

'''Transform features by scaling each feature to a given range.

This estimator scales and translates each feature individually such 
that it is in the given range on the training set, 
e.g. between zero and one.
The transformation is given by:


X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min

'''
from sklearn.preprocessing import MinMaxScaler
import pandas as pd


data=[[-1, 2], [-0.5, 6], [0, 10], [1,18]]

scaler= MinMaxScaler()
"""change the data to the DATA-Frame

to convert from dataframed data to the scaler data by using scaler.fit_transform

"""
mod_value=pd.DataFrame(scaler.fit_transform(data),columns=['c1','c2']) #value converted to Data Frame and fit_transform
print(mod_value)
'''MIN and MAX are aggrigate functions
to do an agrigate funtion ,use groupby(similar to SQL function) to do the mod value'''

mod_value.groupby(lambda l:0).agg(['min','max'])


     c1    c2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  1.00  1.00


c1        c2     
   min  max  min  max
0  0.0  1.0  0.0  1.0

In [33]:
'''unit scaling under from sklearn.preprocessing import StandardScaler'''
from sklearn.preprocessing import StandardScaler

scaler_1=StandardScaler()
scaled_value=pd.DataFrame(scaler_1.fit_transform(data),columns=['c1','c2'])
print(scaled_value)


scaled_value.groupby(lambda l:0).agg(['mean','std'])

         c1        c2
0 -1.183216 -1.183216
1 -0.507093 -0.507093
2  0.169031  0.169031
3  1.521278  1.521278


c1             c2          
  mean       std mean       std
0  0.0  1.154701  0.0  1.154701

In [37]:
'''Scale-function'''

import numpy as np
from sklearn.preprocessing import scale

'''from sklearn.preprocessing import scale using for Standardize a dataset along any axis

Center to the mean and component wise scale to unit variance.'''

x=np.array([
    [0., 0., 5., 13., 9., 1.],
    [0., 0., 13., 15., 10., 15.],
    [0., 3., 15., 2., 0., 11.]
            ])
print(x)
print(scale(x))


[[ 0.  0.  5. 13.  9.  1.]
 [ 0.  0. 13. 15. 10. 15.]
 [ 0.  3. 15.  2.  0. 11.]]
[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]
